<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE queries [
<!ELEMENT queries (query+)>
<!ELEMENT query (#PCDATA)>
<!ATTLIST query id ID #IMPLIED>
]>

<queries>
	<query id="selectTotalCount">
	SELECT count(*) FROM repo
	</query>
	
	<query id="selectTotalCountSearchByDesc">
	SELECT count(*) FROM repo
	WHERE description LIKE ?
	</query>

	<query id="selectTotalCountSearchByLang">
	SELECT count(*) FROM lang
	WHERE name = ?
	</query>

	<query id="selectTotalCountSearchByTag">
	SELECT count(*) FROM tag
	WHERE name = ?
	</query>

	<query id="selectTotalCountSearchByTitle">
	SELECT count(*) FROM repo
	WHERE title LIKE ?
	</query>

	<query id="selectRepos">
	SELECT * FROM repo
	ORDER BY id
	LIMIT ? OFFSET ?
	</query>
	
	<query id="selectReposByDesc">
	SELECT * FROM repo
	WHERE description LIKE ?
	ORDER BY id
	LIMIT ? OFFSET ?
	</query>

	<query id="selectReposByTitle">
	SELECT * FROM repo
	WHERE title LIKE ?
	ORDER BY id
	LIMIT ? OFFSET ?
	</query>

	<query id="selectReposByLang">
	SELECT * FROM repo
	WHERE id IN (
		SELECT id FROM lang
		WHERE name = ?
	) ORDER BY id
	LIMIT ? OFFSET ?
	</query>

	<query id="selectReposByTag">
	SELECT * FROM repo
	WHERE id IN (
		SELECT id FROM tag
		WHERE name = ?
	) ORDER BY id
	LIMIT ? OFFSET ?
	</query>

	<query id="selectLangsById">
	SELECT name FROM lang
	WHERE id = ?
	</query>

	<query id="selectTagsById">
	SELECT name FROM tag
	WHERE id = ?
	</query>
	
</queries>